name: Update Web App on Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: SSH into Azure VM and Update Web App
      uses: appleboy/ssh-action@master
      with:
        host: 20.117.224.131
        username: "azureuser"
        key: ${{ secrets.AZURE_VM_SSH_KEY }}
        script: |
          # Change to your web app directory
          cd /home/azureuser/DevOps

          # Pull the latest changes from GitHub
          git pull origin main

          git clone https://github.com/jrykns-org/not-a-virus-map .


          # Restart your application or perform any necessary steps
          # Replace the following command with your actual command.
          systemctl restart devops
